### ISSUE TITLE
原理演示

### ISSUE THREAD

**Issue by ZephyrJung** [b3log/latke-demo#4]
<del>也算是出于一点私心，想联动b3log和love2d我的两大学习内容，想通过love2d来做latke的原理演示。早就想如此做，但如数据结构或者spring往往量大而复杂，但以latke的小巧，相比做来也不是没有奔头
甚至可以用love2d的demo展示来启动latke的demo演示</del>
改主意了……Love2D经常没时间看，有缘再说了

**Comment by ydcun** [comment]
你好，pox.xml中引用包都没有指定版本为什么呀？

**Comment by ZephyrJung** [comment]
@ydcun 版本号声明在了properties标签内

**Comment by zk-123** [comment]
可以具体说说Latke的IOC容器吗？怎么实现它的

**Comment by ZephyrJung** [comment]
@zk-123 我也在学习中，不知道是不是这个issue引起了你的误会，抱歉
最近过了一遍这个demo的请求响应流程，感觉可以由此入手来理解框架的实现，有兴趣可以看看我这篇博客[通过Latke-Demo对Latke工作流程的初步分析](http://zephyr.b3log.org/articles/2016/11/22/1479809851324.html)

**Comment by zk-123** [comment]
谢谢啦
