### ISSUE TITLE
boolean类型的特殊处理

### ISSUE THREAD

**Issue by qiankunpingtai** [b3log/latke-demo#6]
boolean类型在数据库中对应的是char，能否添加一个过滤boolean类型的例子呢？
我没有深入的研究源码，猜测可能有如下情况，不知道哪一种是对的
第一种：
`filters.add(new PropertyFilter(Article.ARTICLE_DISPLAYABLE, FilterOperator.NOT_EQUAL, false));`
第二种：
`filters.add(new PropertyFilter(Article.ARTICLE_DISPLAYABLE, FilterOperator.NOT_EQUAL, '0'));`

**Comment by 88250** [comment]
第一种应该可以工作。这个很好验证嘛，你自己测试一下就知道了。

另外不建议用 boolean，用 int 表示好一些，设计上也更具有扩展性。

**Comment by qiankunpingtai** [comment]
这里有个问题，基于数据库是char类型，我更倾向于第二种写法，但是基于程序是boolean类型，我更倾向于第一种写法，所以建议楼主在demo中给出一个例子，这个大家可以少走弯路！

**Comment by qiankunpingtai** [comment]
经过测试发现对于boolean类型
第一种：
filters.add(new PropertyFilter(Article.ARTICLE_DISPLAYABLE, FilterOperator.NOT_EQUAL, false));
可以达到过滤效果
第二种：
filters.add(new PropertyFilter(Article.ARTICLE_DISPLAYABLE, FilterOperator.NOT_EQUAL, '0'));
无法达到过滤效果
